### ISSUE TITLE
Issue extending to cover Sentinel 2 imagery

### ISSUE THREAD

**Issue by rustyb** [mapbox/landsat-tiler#2]
I've been attempting to add sentinel 2 routes to the landsat tiler but having little success following deployment to lambda. It works as desired when testing on docker locally. See https://github.com/rustyb/landsat-tiler/commit/803a9735712580f95e5a049c25484dac5b8544a7 

When deployed to lambda I get the following error when trying to get metadata for an S2 scene:

```
{
"ErrorMessage": "'/vsis3/sentinel-s2-l1c/tiles/35/J/PH/2017/8/5/0/preview.jp2' does not exist in the file system, and is not recognized as a supported dataset name."
}
```
I'm assuming its a permissions issue on AWS but not sure.

@vincentsarago maybe you might be able to point me in the right direction?

**Comment by vincentsarago** [comment]
Hey @rustyb you are really close. 
What's happening is GDAL not able to read JP2 because of an environment variable: 
https://github.com/rustyb/landsat-tiler/blob/803a9735712580f95e5a049c25484dac5b8544a7/serverless.yml#L31

You need to change it to `CPL_VSIL_CURL_ALLOWED_EXTENSIONS: ".jp2" to allow gdal to get Jp2 files.

I really appreciate that you already jump on that and trie to make your own sentinel tiler :heart:

That's said, when working on rio-tiler I realized that sentinel-tiler was possible but I wasn't happy with the performances (when using openjpeg 2.2.0). 
Later last week OpenJPEG 2.3 got realized and bring a nice performance improvement (but it still takes couple seconds per tiles). 

I created a [`sentinel-tiler`](https://github.com/mapbox/sentinel-tiler) repo but kept private because I didn't had the time to add a live demo (I was planning to do it later this week). 

Again I'm glad you are trying to create your own, you can fork `sentinel-tiler`, and it's really similar to landsat-tiler. 

If you endup creating a live demo I'll be more than happy to add a link on the readme page. 

Kind regards,

Vincent

**Comment by rustyb** [comment]
Ah amazing I knew it must be something very simple. I now see what you mean, it's certainly not super fast at rendering. Will have a crack at the demo tomorrow.
